export const ITEM_DESCRIPTIONS: Record<string, string> = {
	large_platform_b: 'A base platform with one large and two medium slots for powering and organizing equipment.',
	backpack: 'The Astroneer’s inventory, oxygen reserve, power supply, research catalog, and built-in printer.',
	small_printer: 'A portable printer that creates small automation items and Tier 2 equipment.',
	packager: 'Repackages most deployable objects so they can be carried, stored, or moved more easily.',
	tethers: 'Extend oxygen and power from an oxygenator-equipped network while exploring away from base.',
	oxygen_filters: 'A consumable that temporarily supplies oxygen when the backpack’s reserve runs low.',
	oxygen_tank: 'Adds another tank of breathable oxygen to the backpack’s total reserve.',
	portable_oxygenator: 'Uses backpack power to provide oxygen without a tether connection.',
	small_canister: 'Stores soil gathered with the Terrain Tool for building terrain or using the Soil Centrifuge.',
	beacon: 'A customizable marker that remains visible from a distance and from orbit.',
	worklight: 'A compact directional light that can be attached to the backpack, Terrain Tool, or a slot.',
	glowsticks: 'A bundle of disposable lights that illuminate an area for a limited time.',
	floodlight: 'A strong directional lamp for lighting work areas, caves, vehicles, and bases.',
	small_generator: 'Burns Organic to provide portable power to a connected network.',
	power_cells: 'A consumable stack that supplies a limited amount of power before disappearing.',
	small_solar_panel: 'A portable panel that produces power while exposed to sunlight.',
	small_wind_turbine: 'A portable turbine that produces power whenever local wind is active.',
	small_battery: 'Stores excess network power and releases it when production cannot meet demand.',
	boost_mod: 'Increases the Terrain Tool’s digging and terrain-building speed.',
	wide_mod: 'Expands the Terrain Tool’s affected area for broad excavation and shaping.',
	narrow_mod: 'Shrinks the Terrain Tool’s affected area for precise excavation and shaping.',
	inhibitor_mod: 'Lets the Terrain Tool gather surface objects and apply colors without deforming the ground.',
	alignment_mod: 'Aligns Terrain Tool edits with the local horizontal or vertical direction.',
	drill_mod_1: 'Allows the Terrain Tool to cut through moderately hard terrain.',
	drill_mod_2: 'Allows the Terrain Tool to cut through hard terrain on more difficult planets.',
	drill_mod_3: 'Allows the Terrain Tool to cut through the hardest natural terrain.',
	dynamite: 'A placeable explosive used to destroy terrain, hazards, debris, and many objects.',
	fireworks: 'A single-use rocket that launches a colorful explosion into the sky.',
	small_camera: 'Takes a snapshot when activated manually or by an automation signal.',
	small_trumpet_horn: 'A compact horn that plays a note when activated.',
	holographic_figurine: 'A collectible hologram that displays one of the game’s figurine designs.',
	terrain_analyzer: 'Samples a terrain color and lets the Terrain Tool paint with that color.',
	probe_scanner: 'Points toward undiscovered historical probes on the current planet when activated.',
	solid_fuel_jump_jet: 'A limited-use mobility tool that gives the Astroneer short aerial boosts.',
	hydrazine_jet_pack: 'A reusable flight tool that consumes Hydrazine for sustained aerial movement.',
	hoverboard: 'A fast personal vehicle that carries the Astroneer over terrain while consuming power.',
	medium_printer: 'A printing module used to create Tier 3 base modules, platforms, storage, and vehicles.',
	oxygenator: 'Supplies oxygen to connected platforms, cables, and tether networks.',
	medium_shredder: 'Shreds compatible small items and debris into Scrap.',
	field_shelter: 'A compact shelter that provides oxygen, power, and a save point at remote bases.',
	auto_arm: 'Automatically transfers Tier 1 items between nearby slots and can filter by item type.',
	medium_resource_canister: 'Stores a bulk supply of one solid resource and can dispense it automatically.',
	medium_fluid_soil_canister: 'Stores large amounts of Soil or Hydrazine and can fill or empty connected containers.',
	medium_gas_canister: 'Stores a bulk supply of one atmospheric gas and can dispense it automatically.',
	power_sensor: 'Sends an automation signal when a connected power network changes state.',
	storage_sensor: 'Sends an automation signal when the fill level of attached storage changes.',
	battery_sensor: 'Sends an automation signal when an attached battery’s charge state changes.',
	button_repeater: 'Sends an activation signal to every item connected to its target pins.',
	count_repeater: 'Counts incoming signals and sends one output after reaching its configured total.',
	delay_repeater: 'Waits for a configured interval before passing an automation signal onward.',
	extenders: 'Carry power across a longer cable run, including one-way power when oriented as an arrow.',
	power_switch: 'Manually or automatically connects and disconnects two power networks.',
	splitter: 'Divides a power connection into branches and displays current network flow.',
	medium_generator: 'Consumes Carbon to generate steady power for a connected network.',
	medium_solar_panel: 'Produces network power from sunlight and folds for storage or transport.',
	medium_wind_turbine: 'Produces network power while wind is active and folds for transport.',
	medium_battery: 'Stores excess power and automatically supports a network when generation falls short.',
	large_battery: 'A high-capacity battery that stores excess power and releases it during shortages.',
	rtg: 'Produces constant power without fuel, sunlight, wind, or other operating conditions.',
	medium_platform_a: 'A compact base platform with a single medium slot and cable connections.',
	medium_platform_b: 'A base platform with one medium and two small attachment slots.',
	medium_platform_c: 'A circular base platform with one medium attachment slot.',
	tall_platform: 'Raises a medium slot above the ground for lights, sensors, and compact equipment.',
	medium_t_platform: 'A T-shaped base platform for arranging equipment vertically.',
	medium_stacked_platform: 'A base platform with two medium attachment slots stacked vertically.',
	medium_storage: 'A folding storage rack that provides eight small attachment slots.',
	medium_storage_silo: 'A compact cylindrical storage unit with twenty-four small attachment slots.',
	rover_seat: 'A single-seat control module for operating rovers, tractors, cranes, and other vehicles.',
	tractor: 'A small powered vehicle that tows trailers and provides basic early-game transport.',
	trailer: 'A towable vehicle segment that adds storage, power connections, and another attachment point.',
	medium_buggy_horn: 'A vehicle-mounted horn that plays a note when activated.',
	winch: 'Attaches a physics cable to movable objects so a vehicle or player can tow them.',
	paver: 'Uses Soil to build a road beneath a moving rover, even across gaps and rough ground.',
	drill_strength_1: 'A vehicle drill that mines resources and cuts through moderately hard terrain.',
	drill_strength_2: 'A stronger vehicle drill that cuts through hard terrain while driving.',
	drill_strength_3: 'The strongest vehicle drill, capable of cutting through any natural terrain.',
	solid_fuel_thruster: 'A limited-use shuttle engine that provides several launches before being consumed.',
	hydrazine_thruster: 'A reusable shuttle engine that consumes Hydrazine canisters for launches.',
	rail_post_bundle: 'Unpacks into rail posts used to build a powered railway across terrain.',
	tall_rail_post_bundle: 'Unpacks into taller rail posts for spanning uneven terrain and obstacles.',
	rail_junction_bundle: 'A bundle of junctions that connect and switch between three rail lines.',
	large_printer: 'A large printing module used to create Tier 4 structures, vehicles, and spacecraft.',
	smelting_furnace: 'Refines raw resources such as Laterite and Malachite into usable metals and materials.',
	soil_centrifuge: 'Converts Soil from canisters into selected common natural resources.',
	chemistry_lab: 'Combines resources and atmospheric gases to create advanced composite materials.',
	atmospheric_condenser: 'Collects the atmospheric gases available on the current planet.',
	research_chamber: 'Consumes research items and resources over time to generate Bytes.',
	exo_request_platform: 'Submits event resources to EXO Dynamics and receives event rewards.',
	trade_platform: 'Exchanges Scrap for resources by sending a trade rocket into orbit.',
	large_shredder: 'Shreds compatible items up to Tier 2 and debris into Scrap.',
	large_solar_panel: 'A large deployable panel that produces substantial power in sunlight.',
	large_wind_turbine: 'A large deployable turbine that produces substantial power while wind is active.',
	large_platform_a: 'A base platform with one large attachment slot for equipment or storage.',
	large_platform_c: 'A base platform with one large and twenty small attachment slots.',
	large_t_platform: 'A T-shaped platform with large attachment slots for branching module layouts.',
	large_curved_platform: 'A curved base platform for arranging equipment around a central area.',
	large_extended_platform: 'A long base platform with two medium attachment slots spaced apart.',
	large_stacked_platform: 'A base platform that stacks equipment vertically and adjusts its height to fit.',
	large_resource_canister: 'Stores up to 400 nuggets of one solid resource and can dispense them automatically.',
	large_storage: 'A storage rack with four medium attachment slots.',
	large_storage_silo_a: 'A tall storage unit with eight medium attachment slots arranged around a column.',
	large_storage_silo_b: 'A dense storage unit with twelve medium attachment slots arranged around a column.',
	large_active_storage: 'A movable storage panel with fifteen small attachment slots that responds to automation signals.',
	buggy: 'A fast, lightweight personal vehicle built for scouting and surface travel.',
	large_rover_seat: 'A three-seat control module for operating rovers and carrying a small crew.',
	medium_rover: 'A versatile vehicle with room for equipment, storage, and chained rover segments.',
	crane: 'A vehicle-mounted arm that operates an attached drill head for targeted excavation.',
	large_fog_horn: 'A large horn that plays a deep note when activated.',
	recreational_sphere: 'A large physics ball used for games, goals, and base decoration.',
	gravity_globe: 'A drivable recreational sphere with its own internal gravity and seat.',
	vtol: 'A compact flying vehicle that uses Hydrazine for fast planetary travel.',
	rail_engine: 'A powered railway vehicle that pulls rail cars and follows connected rail lines.',
	rail_car: 'An unpowered railway car that adds storage or passenger capacity to a train.',
	cole: 'A unique rail engine rewarded through the Rails mission chain.',
	shelter: 'A permanent base structure that provides oxygen, power, cable connections, and a save point.',
	auto_extractor: 'Slowly extracts resources from a deposit with much higher yield than manual mining.',
	extra_large_shredder: 'Shreds compatible items up to Tier 3 and debris into Scrap.',
	solar_array: 'A deployable solar generator that produces power when exposed to sunlight.',
	xl_wind_turbine: 'An extra-large turbine that produces high power output while wind is active.',
	medium_sensor_arch: 'An arch with sensor zones that trigger automation when objects pass through.',
	xl_sensor_arch: 'A wide sensor arch that triggers automation when objects pass through its detection zone.',
	xl_sensor_canopy: 'An overhead sensor structure that sends a signal when its detection zone is crossed.',
	large_sensor_ring: 'A circular sensor structure that triggers automation when objects pass through it.',
	large_sensor_hoop_a: 'A large recreational hoop with a sensor that detects objects passing through.',
	large_sensor_hoop_b: 'An alternate large sensor hoop for recreational courses and automation.',
	xl_sensor_hoop_a: 'An extra-large recreational hoop with a built-in pass-through sensor.',
	xl_sensor_hoop_b: 'An alternate extra-large sensor hoop for courses and automation.',
	extra_large_platform_a: 'A base platform with one extra-large attachment slot for large equipment.',
	extra_large_platform_b: 'A base platform with angled attachment surfaces for equipment and storage.',
	extra_large_platform_c: 'A base platform that can hold one extra-large module alongside two large modules.',
	extra_large_curved_platform: 'A curved base platform with two large and one medium attachment slots.',
	xl_extended_platform: 'A long base platform with one large and two medium attachment slots.',
	figurine_platform: 'A chessboard-style platform for arranging Stone and Holographic Figurines.',
	extra_large_storage: 'A massive storage frame that provides thirty-one small attachment slots.',
	large_rover: 'A heavy exploration vehicle with extensive room for modules, storage, and trailers.',
	landing_pad: 'A fixed landing point for shuttles that also provides mission and starting-platform controls.',
	small_shuttle: 'A compact spacecraft with limited cargo space for travel between planets.',
	medium_shuttle: 'A larger spacecraft with more cargo capacity for interplanetary travel.',
	large_shuttle: 'A high-capacity spacecraft for transporting cargo between planets.',
	rail_station: 'Controls train stops and automates loading and unloading rail vehicles.'
};
